# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install frontend dependencies
RUN npm install

# Build the frontend app
RUN npm run build

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the frontend app
CMD ["npm", "start"]