version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=your_database_uri
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
